name: Continuous Integration

on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
     
      - name: Print Output
      
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
  prod-action:
    name: GitHub Actions Prod
    runs-on: ubuntu-latest
    environment: Prod
    steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4
     
        - name: Print Output
          id: output
          run: echo "${{ steps.test-action.outputs.time }}"
